### ISSUE TITLE
Support for FaceID and FingerPrint

### ISSUE THREAD

**Issue by MeiyappanKannappa** [IBM-Security/verify-sdk-android#1]
Can we use IBM Verify SDK for face id and finger print authentication. Is there any sample app for the same?

**Comment by chagemann** [comment]
@MeiyappanKannappa I'm sorry it's taken a while to come back to you on this issue.

If you are asking whether the IBM Security Verify SDK can be used to invoke a biometric authentication dialog: no, it does not support that. It's the responsibility of the app to invoke that dialog and depending on that result, calling the relevant classes and methods of the SDK.

Here is an article that describes those steps as well as some details that you should be aware: https://www.ibm.com/blogs/security-identity-access/create-your-own-authenticator/
